version: '3.1'

services:
# Definiciones para la base de datos
  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    hostname: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    networks:
      - db
    volumes:
      - db-data:/data/db

# Definiciones para aplicación
  application:
    image: nextjs-app
    container_name: nextjs-app
    ports:
      - "3000:3000"
    networks:
      - db
    depends_on:
      - mongo
    links:
      - mongo:db
networks:
  db:
volumes:
  db-data:
